# Generated by Django 5.0.3 on 2024-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='SongArtist',
            field=models.ManyToManyField(to='Songs.artist'),
        ),
    ]
